### ISSUE TITLE
Red5 Service does not start on Windows

### ISSUE THREAD

**Issue by maujood** [Red5/red5-service#6]
I am able to run and use the Red5 server using red5.bat and red5-shutdown.bat, but the Red5 Media Server service does not start with service-specific error code 4. I installed it using install-service.bat.

Following is what I see in the logs:

### red5-error.log

2016-12-09 18:38:24 Commons Daemon procrun stderr initialized
java.lang.NoClassDefFoundError: Main
Caused by: java.lang.ClassNotFoundException: Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Exception in thread "main" 

### commons-daemon.???.log

[2016-12-09 18:38:24] [info]  [ 9360] Commons Daemon procrun (1.0.14.0 64-bit) started
[2016-12-09 18:38:24] [info]  [ 9360] Running 'Red5' Service...
[2016-12-09 18:38:25] [info]  [ 9948] Starting service...
[2016-12-09 18:38:25] [error] [ 7504] FindClass Main failed
[2016-12-09 18:38:25] [error] [ 9948] Failed to start Java
[2016-12-09 18:38:25] [error] [ 9948] ServiceStart returned 4
[2016-12-09 18:38:25] [info]  [ 9360] Run service finished.
[2016-12-09 18:38:25] [info]  [ 9360] Commons Daemon procrun finished

Is this an issue with the Red5 service?

**Comment by mondain** [comment]
We've found this happens on a number of windows versions after Win 7; with all things being the same, we assume the problem lies in the native procrun code.

**Comment by maujood** [comment]
I see. For now, I have just created a scheduled task that runs Red5.bat on startup as a workaround.

**Comment by Desmond-Liu** [comment]
I have the same problem, and my OS is Win10.

**Comment by mondain** [comment]
Apache recently fixed an issue with procrun in commons-daemon 1.2.2; hopefully that resolves this problem.

**Comment by bratwurzt** [comment]
The problem is still present. Windows10 + commons-daemon-1.2.2 and am still getting:
[2019-10-31 14:39:31] [info]  [11548] Apache Commons Daemon procrun (1.2.2.0 64-bit) started.
[2019-10-31 14:39:31] [info]  [11548] Running Service 'Red5'...
[2019-10-31 14:39:31] [info]  [ 3228] Starting service...
[2019-10-31 14:39:31] [error] [10924] FindClass Main failed
[2019-10-31 14:39:31] [error] [ 3228] Failed to start Java
[2019-10-31 14:39:31] [error] [ 3228] ServiceStart returned 4.
[2019-10-31 14:39:31] [info]  [11548] Run service finished.

**Comment by mondain** [comment]
I'll try to slot some time this weekend to run it on my win 10 laptop.

**Comment by mondain** [comment]
I learned from this https://bz.apache.org/bugzilla/show_bug.cgi?id=63767 that a "fully-patched" windows is required to work with the daemon lib; please ensure that your OS is up-to-date.

**Comment by AffiTheCreator** [comment]
Anys news on this issue?

**Comment by soulspirits** [comment]
still ocurred at my win10 21H2, 囧。
